### ISSUE TITLE
Doesn't work with GNOME Terminal in Wayland session

### ISSUE THREAD

**Issue by anupam207** [franglais125/no-title-bar#24]
Title bar doesn't go away if I maximize GNOME Terminal in Wayland session. I noticed this for Terminal, but I think it happens with all the windows running in Wayland. Windows running in XWayland, for example Firefox, seem to behave as expected.

Distro: Ubuntu GNOME 17.04, shell version 3.24.2

**Comment by franglais125** [comment]
Hi, thanks for taking the time of opening an issue!

In this case, unfortunately there is nothing I can do. This extension only works on X and on XWayland windows. Since GNOME terminal runs natively on Wayland, I can't remove the title bar.

Note that this is not a problem with the extension, or something I can fix, it simply can't be done with an extension.

For more info you can look at this issue https://github.com/franglais125/no-title-bar/issues/19.

Sorry! And cheers!

**Comment by anupam207** [comment]
No problem. Thanks for your quick reply. Strange to see Terminal not using client side decoration like other GNOME apps. Hope they'll fix it soon.

**Comment by franglais125** [comment]
Indeed, I'd like that too!

Closing...

**Comment by franglais125** [comment]
I got this working on Wayland with the latest version from git. Would you mind testing it?

**Comment by anupam207** [comment]
@franglais125 I've moved back to Xorg as so many things were not working with Wayland :( I'll test the new version as soon as I start trying Wayland again. But can't promise it'll be very soon :(

**Comment by morphheus** [comment]
As of today, on a fresh gnome 3.26 install, gnome-terminal does not work on Wayland.

**Comment by franglais125** [comment]
@morphheus great to know that it works for you :). And yes, a relogin is necessary.
