### ISSUE TITLE
Title bar hidden only on applications on primary desktop

### ISSUE THREAD

**Issue by sjug** [franglais125/no-title-bar#58]
Hello there,

Using GNOME 3.26.2, no-title-bar extension version 8. All applications work perfectly when they are on the primary desktop. 

However if you move them or start them on any other desktop, they are maximized with the title bar still visible. There are no errors for gnome-shell in the journal and I can take a screenshot but it's just exactly how the window looks if the plugin was disabled.

Is there anything else I can do to debug this?

**Comment by franglais125** [comment]
When you say on the primary desktop, do you mean monitor? If so, you can disable ththe following int he settings:

![screenshot from 2018-02-26 10-42-39](https://user-images.githubusercontent.com/19195975/36679693-d2aa51a0-1ae1-11e8-9c08-6524704d5985.png)

Otherwise, could you please send a screenshot?

**Comment by sjug** [comment]
Yes that's exactly it. Thank you very much for your fast reply, and my apologies.
