### ISSUE TITLE
[Question] Does this extension  work with mutter apps (nautilus, gnome-tweaks and etc.)

### ISSUE THREAD

**Issue by ceyhunn** [franglais125/no-title-bar#68]

**Comment by franglais125** [comment]
Thanks for opening this issue. This extension won't work with windows using CSD (such as Nautilus, gnome-tweaks, gedit).

It *can* work with gnome apps (like gnome-terminal) even on Wayland, as we use css styling for that. I hope this answers your question. Let me know if you there are other cases you might have in mind.

**Comment by ceyhunnabiyev** [comment]
Thank you for the answer.

**Comment by ceyhunnabiyev** [comment]
@franglais125 , can be  titlebar buttons (close, maximize, minimize) manually added to top panel by the extension in csd windows? 
By gsettings option  titlebar buttons can be removed. It would be nice to make all window control buttons place on the top panel. Otherwise  different window control view doesn't look cool, also can be confused. What do you think about it?
