### ISSUE TITLE
LibreOffice apps get a black bar instead of titlebar when launched on full screen

### ISSUE THREAD

**Issue by adalvigi** [franglais125/no-title-bar#80]
As title says, LibreOffice Writer, Impress, etc... seem to have this weird issue on my system (Ubuntu Gnome 16.04). They get the controls on the Gnome Top Bar, but instead of having the title bar hidden they have a black bar. If I do minimize and then full screen again the issue is gone and the titlebar is correctly hidden, but it can be annoying if you're used to close and re open LibreOffice several times (like, when consulting multiple documents).

**Comment by franglais125** [comment]
Thanks for reporting this issue! I've experienced this myself in the past. Not much I can do it about it... What I can tell you is that the issue was resolved upstream (Gnome Shell) by adding a smarter redraw when the titlebar is hidden. So the issue should go away once you upgrade to 18.04 (or something as new).
